# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'app_menu',
            },
        ),
        migrations.CreateModel(
            name='ItemsApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=20, verbose_name='Название подпункта')),
                ('href', models.CharField(max_length=20, verbose_name='Вторая часть url')),
            ],
            options={
                'db_table': 'items_app',
            },
        ),
        migrations.CreateModel(
            name='ItemsMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=100, verbose_name='Ссылка')),
                ('text', models.CharField(max_length=100, verbose_name='Подпись')),
            ],
            options={
                'db_table': 'items_menu',
            },
        ),
        migrations.CreateModel(
            name='UserMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.ItemsMenu')),
            ],
            options={
                'db_table': 'user_menu',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='Логин')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='usermenu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.Users'),
        ),
        migrations.AddField(
            model_name='appmenu',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.ItemsMenu'),
        ),
        migrations.AddField(
            model_name='appmenu',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.ItemsApp'),
        ),
    ]
