# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('href', models.CharField(max_length=100, verbose_name='Ссылка')),
                ('text', models.CharField(max_length=100, verbose_name='Подпись')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemsUsers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.Items')),
            ],
            options={
                'db_table': 'items_users',
            },
        ),
    ]
