# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsApps',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.Items')),
            ],
            options={
                'db_table': 'items_apps',
            },
        ),
    ]
