# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsapp',
            name='after',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='itemsapp',
            name='before',
            field=models.CharField(default='', max_length=20),
        ),
    ]
