# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0005_itemsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.ItemsMenu', verbose_name='Приложение')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.ItemsApp', verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Меню приложения',
                'verbose_name_plural': 'Меню приложений',
                'db_table': 'app_menu',
            },
        ),
    ]
