# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlane',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('code', models.CharField(max_length=5)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('lanch', models.BooleanField(default=True)),
                ('break_day', models.SmallIntegerField(default=2)),
                ('break_night', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'work_plane',
            },
        ),
        migrations.AlterUniqueTogether(
            name='workplane',
            unique_together=set([('date_start', 'code')]),
        ),
    ]
