# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0002_auto_20170827_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShedulePlane',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(unique=True)),
                ('shift', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'shedule_plane',
            },
        ),
    ]
