# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0003_sheduleplane'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheduleReal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(unique=True)),
                ('start', models.TimeField(null=True)),
                ('end', models.TimeField(null=True)),
                ('lanch', models.BooleanField(default=True)),
                ('break_day', models.SmallIntegerField(default=2, null=True)),
                ('break_night', models.SmallIntegerField(default=0, null=True)),
                ('delay', models.TimeField(default='00:00', null=True)),
                ('vacation', models.BooleanField(default=False)),
                ('sick', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shedule_real',
            },
        ),
    ]
