# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0006_auto_20170827_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodesPayslip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('i', 'Income'), ('c', 'Consumption'), ('o', 'Others')], max_length=1)),
            ],
            options={
                'db_table': 'codes_payslip',
            },
        ),
    ]
