# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0009_auto_20170827_0403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodesPayslip',
            new_name='PayslipCodes',
        ),
        migrations.AlterModelTable(
            name='payslipcodes',
            table='payslip_codes',
        ),
    ]
