# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
