# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(unique=True)),
                ('work', models.BooleanField(default=True)),
                ('week', models.BooleanField(default=False)),
                ('holiday', models.BooleanField(default=False)),
                ('short', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'signs',
            },
        ),
    ]
