# Generated by Django 3.0.4 on 2020-03-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0003_create_humans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(db_index=True, default=False)),
                ('human', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sheduler.Humans')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sheduler.Locations')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sheduler.Tasks')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'ordering': ['human', 'location', 'task'],
                'unique_together': {('human', 'location', 'task')},
            },
        ),
    ]
