# Generated by Django 3.0.4 on 2020-03-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0005_correctly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependences', to='sheduler.Details', verbose_name='Задача')),
                ('prev_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_details', to='sheduler.Details', verbose_name='Предыдущая задача')),
            ],
            options={
                'verbose_name': 'Зависимость',
                'verbose_name_plural': 'Зависимости',
            },
        ),
    ]
