# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers_app', '0004_mothers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('bit', models.PositiveSmallIntegerField(null=True, verbose_name='Разрядность')),
                ('out_socket', models.CharField(max_length=10, verbose_name='Выходной разъём')),
                ('frequency_count', models.PositiveSmallIntegerField(null=True, verbose_name='Частота')),
                ('frequency_text', models.CharField(max_length=10, null=True, verbose_name='Единица измерения частоты')),
                ('mac', models.CharField(max_length=17, verbose_name='МАС-адрес')),
                ('is_boot', models.BooleanField(verbose_name='Признак возможности загрузки по сети')),
                ('is_wol', models.BooleanField(verbose_name='Признак возможности включения по сети')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='Комментарий')),
            ],
            options={
                'db_table': 'networks',
            },
        ),
    ]
