# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers_app', '0005_networks'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAMs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('type', models.CharField(max_length=20, verbose_name='Тип')),
                ('volume_count', models.PositiveSmallIntegerField(verbose_name='Объём памяти')),
                ('volume_text', models.CharField(max_length=5, verbose_name='Единица измерения объёма')),
                ('bit', models.PositiveSmallIntegerField(null=True, verbose_name='Разрядность')),
                ('frequency_count', models.PositiveSmallIntegerField(null=True, verbose_name='Частота')),
                ('frequency_text', models.CharField(max_length=5, null=True, verbose_name='Единица измерения частоты')),
                ('time', models.CharField(max_length=100, null=True, verbose_name='Тайминги')),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Напряжение питания')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='Комментарий')),
            ],
            options={
                'db_table': 'rams',
            },
        ),
    ]
