# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers_app', '0012_auto_20170827_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCommands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
            ],
            options={
                'db_table': 'system_commands',
            },
        ),
    ]
