# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers_app', '0013_systemcommands'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDoings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(verbose_name='Код процедуры')),
                ('task', models.CharField(max_length=100, null=True, verbose_name='Сообщение пользователю')),
                ('is_need', models.BooleanField(default=True, verbose_name='Обязательность выполнения')),
                ('is_args', models.BooleanField(default=False, verbose_name='Необходимость параметров')),
                ('is_loop', models.BooleanField(default=False, verbose_name='Цикличность')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='Комментарий')),
                ('command', models.ForeignKey(db_column='command', null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers_app.SystemCommands', verbose_name='Команда')),
                ('type', models.ForeignKey(db_column='type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers_app.StaffTypes', verbose_name='Тип обслуживания')),
            ],
            options={
                'db_table': 'staff_doings',
            },
        ),
    ]
