# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers_app', '0003_hdds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mothers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('chipset', models.CharField(max_length=20, verbose_name='Чипсет')),
                ('maker', models.CharField(max_length=20, verbose_name='Производитель')),
                ('factor', models.CharField(max_length=10, verbose_name='Форм-фактор')),
                ('socket', models.CharField(max_length=10, verbose_name='Сокет')),
                ('frequency_bus', models.CharField(max_length=20, null=True, verbose_name='Частота системной шины')),
                ('ram_count', models.PositiveSmallIntegerField(verbose_name='Количество слотов ОП')),
                ('ram_type', models.CharField(max_length=20, verbose_name='Тип ОП')),
                ('is_dual', models.BooleanField(verbose_name='Признак поддержки двухканального режима ОП')),
                ('pcie', models.PositiveSmallIntegerField(verbose_name='Количество слотов PCI-Express')),
                ('pci', models.PositiveSmallIntegerField(verbose_name='Количество слотов PCI')),
                ('ps', models.PositiveSmallIntegerField(null=True, verbose_name='Количество выходов PS/2')),
                ('usb_count', models.PositiveSmallIntegerField(verbose_name='Количество выходов USB')),
                ('usb_type', models.CharField(max_length=20, null=True, verbose_name='Тип USB')),
                ('ide', models.PositiveSmallIntegerField(null=True, verbose_name='Количество слотов IDE')),
                ('sata', models.PositiveSmallIntegerField(null=True, verbose_name='Количество слотов SATA')),
                ('is_video', models.BooleanField(verbose_name='Признак наличия видеокарты')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='Комментарий')),
            ],
            options={
                'db_table': 'mothers',
            },
        ),
    ]
