# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers_app', '0006_rams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('cpu_name', models.CharField(max_length=20, verbose_name='Название процессора')),
                ('cpu_frequency_count', models.PositiveSmallIntegerField(null=True, verbose_name='Частота процессора')),
                ('cpu_frequency_text', models.CharField(max_length=10, null=True, verbose_name='Единица измерения частоты процессора')),
                ('memory_volume_count', models.PositiveSmallIntegerField(verbose_name='Объём памяти')),
                ('memory_volume_text', models.CharField(max_length=10, verbose_name='Единица измерения объёма памяти')),
                ('memory_type', models.CharField(max_length=10, null=True, verbose_name='Тип памяти')),
                ('memory_frequency_count', models.PositiveSmallIntegerField(null=True, verbose_name='Частота памяти')),
                ('memory_frequency_text', models.CharField(max_length=5, null=True, verbose_name='Единица измерения частоты памяти')),
                ('memory_bit', models.PositiveSmallIntegerField(null=True, verbose_name='Разрядность памяти')),
                ('tech', models.CharField(max_length=10, null=True, verbose_name='Техпроцесс')),
                ('vga', models.PositiveSmallIntegerField(verbose_name='Количество выходов VGA')),
                ('dvi', models.PositiveSmallIntegerField(verbose_name='Количество выходов DVI')),
                ('hdmi', models.PositiveSmallIntegerField(verbose_name='Количество выходов HDMI')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='Комментарий')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
