# Generated by Django 4.2.11 on 2024-03-17 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phones', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['city', 'address'],
            },
        ),
        migrations.CreateModel(
            name='TravelStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Состояние поездки',
                'verbose_name_plural': 'Состояния поездки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('participants', models.CharField(max_length=255)),
                ('points', models.ManyToManyField(to='travels.place')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travels.travelstates')),
            ],
            options={
                'verbose_name': 'Путешествие',
                'verbose_name_plural': 'Путешествия',
                'ordering': ['-datetime_start', '-datetime_end'],
                'unique_together': {('datetime_start', 'datetime_end')},
            },
        ),
    ]
