# Generated by Django 4.2.11 on 2024-03-17 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Состояние поездки',
                'verbose_name_plural': 'Состояния поездки',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phones',
            field=models.CharField(max_length=255, verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='datetime_end',
            field=models.DateTimeField(verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='datetime_start',
            field=models.DateTimeField(verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='participants',
            field=models.CharField(max_length=255, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='points',
            field=models.ManyToManyField(blank=True, to='travels.place', verbose_name='Путевые точки'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travels.travelstate', verbose_name='Состояние'),
        ),
        migrations.DeleteModel(
            name='TravelStates',
        ),
    ]
