# Generated by Django 4.2.11 on 2024-03-18 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_travelstate_alter_place_address_alter_place_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='points',
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('doing', models.CharField(db_index=True, max_length=10, verbose_name='Действие')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travels.place', verbose_name='Место')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travels.travel', verbose_name='Путешествие')),
            ],
            options={
                'verbose_name': 'Путевая точка',
                'verbose_name_plural': 'Путевые точки',
                'ordering': ['-datetime'],
            },
        ),
    ]
