# Generated by Django 4.2.11 on 2024-03-18 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_remove_travel_points_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to='travels.travel', verbose_name='Путешествие'),
        ),
    ]
