# Generated by Django 4.2.11 on 2024-03-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_alter_point_travel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['datetime'], 'verbose_name': 'Путевая точка', 'verbose_name_plural': 'Путевые точки'},
        ),
    ]
