# Generated by Django 4.2.11 on 2024-03-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_travel_fuel_consumption_alter_way_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='fuel_price',
            field=models.DecimalField(decimal_places=2, default=56, max_digits=5, verbose_name='Цена топлива'),
            preserve_default=False,
        ),
    ]
