# Generated by Django 4.2.11 on 2024-03-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_travel_fuel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TollRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('start', models.CharField(max_length=255, verbose_name='Начало')),
                ('end', models.CharField(max_length=255, verbose_name='Конец')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Платная дорога',
                'verbose_name_plural': 'Платные дороги',
            },
        ),
    ]
