# Generated by Django 4.2.11 on 2024-03-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_tollroad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollroad',
            name='travel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='toll_roads', to='travels.travel', verbose_name='Путешествие'),
            preserve_default=False,
        ),
    ]
