# Generated by Django 4.2.11 on 2024-03-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_tollroad_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('arrival', models.DateTimeField(verbose_name='Заезд')),
                ('departure', models.DateTimeField(verbose_name='Отъезд')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('state', models.TextField(verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Гостиница',
                'verbose_name_plural': 'Гостиницы',
            },
        ),
    ]
