# Generated by Django 4.2.11 on 2024-03-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_hotel_travel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Путешествие', 'verbose_name_plural': 'Путешествия'},
        ),
        migrations.AlterUniqueTogether(
            name='travel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='travel',
            name='datetime_end',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='datetime_start',
        ),
    ]
