# Generated by Django 4.2.11 on 2024-03-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0014_way_travel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
    ]
