# Generated by Django 4.2.11 on 2024-03-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kladr', '0006_address_name'),
        ('travels', '0015_alter_place_options_remove_hotel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kladr.address', verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kladr.address', verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
