# Generated by Django 4.2.11 on 2024-03-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kladr', '0006_address_name'),
        ('travels', '0018_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
        migrations.AlterField(
            model_name='point',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kladr.address', verbose_name='Место'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
