# Generated by Django 4.2.11 on 2024-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0019_remove_hotel_name_alter_point_place_delete_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='place',
            new_name='address',
        ),
        migrations.AddField(
            model_name='point',
            name='odometer',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
