# Generated by Django 4.2.11 on 2024-04-27 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0020_rename_place_point_address_point_odometer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Путевая точка', 'verbose_name_plural': 'Путевые точки'},
        ),
        migrations.RemoveField(
            model_name='point',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='point',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='way',
            name='travel',
        ),
        migrations.AddField(
            model_name='point',
            name='arrival_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время прибытия'),
        ),
        migrations.AddField(
            model_name='point',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отъезда'),
        ),
        migrations.AddField(
            model_name='travel',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(1988, 11, 30, 20, 0), verbose_name='Дата и вемя окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(1988, 11, 30, 20, 0), verbose_name='Дата и время начала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='doing',
            field=models.CharField(choices=[('U', 'Неизвестно'), ('N', 'Ночёвка'), ('S', 'Перерыв'), ('R', 'Заправка')], default='U', max_length=1, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='state',
            field=models.CharField(choices=[('U', 'Неизвестно'), ('P', 'Планирование'), ('R', 'Выполнение'), ('S', 'Завершена'), ('C', 'Отменена')], default='U', max_length=1, verbose_name='Состояние'),
        ),
        migrations.DeleteModel(
            name='TravelState',
        ),
    ]
