# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_paytypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refuels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check_number', models.CharField(max_length=5)),
                ('dispencer', models.SmallIntegerField()),
                ('fuel_count', models.DecimalField(decimal_places=3, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('score_plus', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('score_minus', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('score_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('date_time', models.DateTimeField()),
                ('odometer', models.DecimalField(decimal_places=1, max_digits=5)),
                ('consumption', models.DecimalField(decimal_places=1, max_digits=4)),
                ('speed', models.PositiveSmallIntegerField()),
                ('azs', models.ForeignKey(db_column='azs', default=1, on_delete=models.SET(1), to='car_app.Azs')),
                ('fuel_type', models.ForeignKey(db_column='fuel_type', on_delete=models.SET(1), to='car_app.FuelTypes')),
                ('pay_type', models.ForeignKey(db_column='pay_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.PayTypes')),
            ],
            options={
                'db_table': 'refuels',
            },
        ),
    ]
