# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrefs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'links',
            },
        ),
    ]
