# Generated by Django 3.0.4 on 2020-04-03 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calend', '0001_create_signs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=50)),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calend.Signs')),
            ],
            options={
                'verbose_name': 'Отметка',
                'verbose_name_plural': 'Отметки',
                'ordering': ['date', 'sign', 'comment'],
                'unique_together': {('date', 'sign', 'comment')},
            },
        ),
    ]
