# Generated by Django 3.0.4 on 2020-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calend', '0005_auto_20200408_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
