# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_fueltypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('card_num', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pay_types',
            },
        ),
    ]
