# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='humans',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='humans',
            name='deadday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='humans',
            name='father_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
