# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans_app', '0003_auto_20171104_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='humans',
            name='first_family',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='humans',
            name='sex',
            field=models.NullBooleanField(choices=[(None, 'Пол'), (True, 'Мужской'), (False, 'Женский')]),
        ),
    ]
