# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('data', models.DateField(primary_key=True, serialize=False, verbose_name='Дата')),
                ('is_vacation', models.BooleanField(default=False, verbose_name='Признак отпуска')),
                ('is_sick', models.BooleanField(default=False, verbose_name='Призак больничного')),
            ],
            options={
                'db_table': 'shedule',
            },
        ),
        migrations.CreateModel(
            name='WorkPlane',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('start', models.TimeField(verbose_name='Начало смены')),
                ('end', models.TimeField(verbose_name='Окончание смены')),
                ('hour', models.IntegerField(verbose_name='Рабочие часы')),
            ],
            options={
                'db_table': 'work_plane',
            },
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baltbank_app.WorkPlane'),
        ),
    ]
