# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
