# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_orgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('summa', models.DecimalField(decimal_places=4, max_digits=11)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('card', models.ForeignKey(db_column='card', default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='budget_app.Cards')),
                ('payer', models.ForeignKey(db_column='payer', default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='budget_app.Orgs')),
                ('type', models.ForeignKey(db_column='type', default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='budget_app.DebetTypes')),
            ],
            options={
                'db_table': 'debets',
            },
        ),
    ]
