# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0008_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheques',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=5, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('kassa', models.IntegerField(null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('card', models.ForeignKey(db_column='card', default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='budget_app.Cards')),
                ('org', models.ForeignKey(db_column='org', default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='budget_app.Orgs')),
            ],
            options={
                'db_table': 'cheques',
            },
        ),
    ]
