# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0009_cheques'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('count', models.DecimalField(decimal_places=4, max_digits=9)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=9, null=True)),
                ('is_need', models.BooleanField(default=True)),
                ('cheque', models.ForeignKey(db_column='cheque', default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='budget_app.Cheques')),
                ('product', models.ForeignKey(db_column='product', default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='budget_app.Products')),
            ],
            options={
                'db_table': 'credits',
            },
        ),
    ]
