# Generated by Django 3.0.4 on 2020-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0001_create_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['name'],
            },
        ),
    ]
