# Generated by Django 3.0.4 on 2020-04-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0006_create_dependences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='is_done',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Выполнено'),
        ),
    ]
