# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0007_credcats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dimension', models.CharField(choices=[('шт.', 'штуки'), ('кг.', 'килограммы'), ('л.', 'литры')], max_length=20)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(db_column='category', default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='budget_app.CredCats')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
