# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-27 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShedulePlane',
            fields=[
                ('data', models.DateField(primary_key=True, serialize=False)),
                ('shift', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'shedule_plane',
            },
        ),
        migrations.CreateModel(
            name='WorkPlane',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('code', models.CharField(max_length=5)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('break_day', models.SmallIntegerField(default=2)),
                ('break_night', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'work_plane',
            },
        ),
        migrations.AlterUniqueTogether(
            name='workplane',
            unique_together=set([('date_start', 'code')]),
        ),
    ]
