# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0005_auto_20170827_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateField()),
                ('end', models.DateField(null=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
            options={
                'db_table': 'rate',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('start', 'end')]),
        ),
    ]
