# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0010_auto_20171201_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payslip',
            new_name='Payslips',
        ),
        migrations.AlterModelTable(
            name='payslips',
            table='payslips',
        ),
    ]
