# Generated by Django 4.2.11 on 2024-03-25 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kladr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('short', models.CharField(max_length=5, verbose_name='Сокращённое название')),
            ],
            options={
                'verbose_name': 'Тип населённого пункта',
                'verbose_name_plural': 'Типы населённых пунктов',
            },
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['code'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cyties', to='kladr.region', verbose_name='Регион')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cityes', to='kladr.citytype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
            },
        ),
    ]
