# Generated by Django 4.2.11 on 2024-03-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kladr', '0003_streettype_remove_city_region_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='citytype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='streettype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('type', 'name')},
        ),
    ]
