# Generated by Django 4.2.11 on 2024-03-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kladr', '0004_alter_city_name_alter_citytype_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('building', models.CharField(blank=True, max_length=5, null=True, verbose_name='Строение/корпус/литера')),
                ('flat', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Квартира')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='kladr.city', verbose_name='Населённый пункт')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='kladr.region', verbose_name='Регион')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='kladr.street', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
