# Generated by Django 4.2.11 on 2024-03-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kladr', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Дом', max_length=20, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
