# Generated by Django 4.2.11 on 2024-04-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objects',
            new_name='Object',
        ),
    ]
