# Generated by Django 3.0.4 on 2020-04-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calend', '0002_create_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='comment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
