# Generated by Django 3.0.4 on 2020-04-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calend', '0003_alter_marks_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('type', models.CharField(choices=[('Р', 'Рабочий'), ('В', 'Выходной'), ('П', 'Праздничный')], db_index=True, max_length=1)),
                ('comment', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['date'],
            },
        ),
    ]
