# Generated by Django 3.0.4 on 2020-04-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calend', '0004_create_productions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productions',
            name='type',
            field=models.CharField(choices=[('Р', 'Рабочий'), ('В', 'Выходной'), ('П', 'Праздничный'), ('С', 'Сокращённый')], db_index=True, max_length=1),
        ),
    ]
