# Generated by Django 3.0.4 on 2020-04-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calend', '0006_alter_marks_add_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signs',
            options={'ordering': ['name'], 'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterField(
            model_name='marks',
            name='comment',
            field=models.CharField(max_length=50, null=True, verbose_name='Напоминание'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calend.Signs', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='signs',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
