# Generated by Django 4.2.11 on 2024-03-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Топливо',
                'verbose_name_plural': 'Топливо',
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Организация')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'АЗС',
                'verbose_name_plural': 'АЗСы',
            },
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер чека')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('trk', models.PositiveSmallIntegerField(default=3, verbose_name='ТРК №')),
                ('count', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.fuel', verbose_name='Топливо')),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.fuelstation', verbose_name='АЗС')),
            ],
            options={
                'verbose_name': 'Дозаправка',
                'verbose_name_plural': 'Дозаправки',
            },
        ),
    ]
