# Generated by Django 4.2.11 on 2024-03-25 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refuel',
            name='distance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Межзаправочный пробег'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refuel',
            name='distance_reserve',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Запас хода'),
        ),
        migrations.AddField(
            model_name='refuel',
            name='fuel_consumption',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=4, verbose_name='Межзаправочный расход топлива'),
        ),
        migrations.AddField(
            model_name='refuel',
            name='fuel_consumption_avf',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=3, verbose_name='Расход топлива общий'),
        ),
        migrations.AddField(
            model_name='refuel',
            name='odometer',
            field=models.PositiveIntegerField(default=0, verbose_name='Общий пробег'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refuel',
            name='timedelta',
            field=models.CharField(default='00:00', max_length=5, verbose_name='Временной интервал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refuel',
            name='fuel_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refuels', to='car.fuelstation', verbose_name='АЗС'),
        ),
    ]
