# Generated by Django 4.2.11 on 2024-03-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_refuel_distance_refuel_distance_reserve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refuel',
            old_name='fuel_consumption_avf',
            new_name='fuel_consumption_avg',
        ),
    ]
