# Generated by Django 4.2.11 on 2024-03-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_rename_fuel_consumption_avf_refuel_fuel_consumption_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelstation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='fuelstation',
            name='name',
        ),
    ]
