# Generated by Django 4.2.11 on 2024-03-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kladr', '0006_address_name'),
        ('car', '0004_remove_fuelstation_address_remove_fuelstation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kladr.address', verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
