# Generated by Django 4.2.11 on 2024-04-06 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_fuelstation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='fuel_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fuels', to='car.fuelstation', verbose_name='АЗС'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='name',
            field=models.CharField(default='Unknown', max_length=20, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
