# Generated by Django 4.2.11 on 2024-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_fuel_fuel_station_fuelstation_name_fuelstation_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='fuel_station',
        ),
        migrations.RemoveField(
            model_name='fuelstation',
            name='name',
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
