# Generated by Django 4.2.11 on 2024-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_remove_fuel_fuel_station_remove_fuelstation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='refuel',
            name='datetime',
            field=models.DateTimeField(unique=True, verbose_name='Дата и время'),
        ),
        migrations.AlterUniqueTogether(
            name='fuelstation',
            unique_together={('company', 'number')},
        ),
    ]
