# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'event_types',
            },
        ),
        migrations.CreateModel(
            name='Humans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('deadday', models.DateField()),
                ('comment', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'humans',
            },
        ),
        migrations.CreateModel(
            name='HumansRelations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('human_1', models.ForeignKey(db_column='human_1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_1', to='humans_app.Humans')),
                ('human_2', models.ForeignKey(db_column='human_2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_2', to='humans_app.Humans')),
            ],
            options={
                'db_table': 'humans_relations',
            },
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'relations',
            },
        ),
        migrations.AddField(
            model_name='humansrelations',
            name='relation',
            field=models.ForeignKey(db_column='relation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='humans_app.Relations'),
        ),
        migrations.AddField(
            model_name='events',
            name='human',
            field=models.ForeignKey(db_column='human', null=True, on_delete=django.db.models.deletion.SET_NULL, to='humans_app.Humans'),
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.ForeignKey(db_column='type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='humans_app.EventTypes'),
        ),
    ]
